mkdir data
mkdir data/discord-steem
mkdir data/discord-hive
mkdir data/finished-steem
mkdir data/finished-hive
mkdir data/memeber-steem
mkdir data/member-hive
mkdir data/post-steem
mkdir data/post-hive
mkdir data/created-steem
mkdir data/created-hive
mkdir data/altruism-steem
mkdir data/altruism-hive
mkdir data/notnew-steem
mkdir data/notnew-hive
mkdir data/posters-steem
mkdir data/posters-hive
mkdir data/cancelled-steem
mkdir data/cancelled-hive
mkdir data/advertorial-steem
mkdir data/advertorial-hive
