const randomFile = require('select-random-file')
const tor_axios = require('tor-axios');
const tor = tor_axios.torSetup({
    ip: 'localhost',
    port: 9050,
    controlPort: '9051',
    controlPassword: 'giraffe',
})
const Curl = require('node-libcurl').Curl;

const cheerio = require('cheerio');

const sentences = [
    "This post shows evidence of plagiarism",
    "The writing style suggests this post is not original",
    "The content of this post has been copied from elsewhere",
    "This post contains many grammatical errors, which may indicate that it was written by a bot",
    "The language used in this post is unnatural and robotic",
    "This post is very similar to others found online",
    "There is little original content in this post",
    "It appears that this post was generated automatically",
    "The writing in this post is lacking in personality and style",
    "The content of this post is generic and unremarkable",
    "There is evidence of copy-pasting in this post",
    "This post reads like it was translated poorly from another language",
    "The language used in this post is overly formal and stilted",
    "The writing in this post is repetitive and monotonous",
    "This post appears to be a regurgitation of existing material",
    "There is little evidence of original thought in this post",
    "The structure of this post is formulaic and predictable",
    "This post seems to be produced by an article spinner",
    "The writing in this post lacks the creative spark of original content",
    "There are many instances of word-for-word copying in this post",
    "This post reads like it was generated by a machine",
    "The writing in this post is devoid of personality",
    "There is little variation in the sentence structure of this post",
    "This post appears to have been plagiarized from multiple sources",
    "The language used in this post is overly technical and jargon-heavy",
    "The content of this post is repetitive and lacks originality",
    "It seems that this post was written by someone with a poor grasp of the language",
    "There are many instances of poor grammar and awkward phrasing in this post",
    "This post is riddled with errors and inconsistencies",
    "The writing in this post lacks the voice and perspective of a human author",
    "There is little evidence of research or personal experience in this post",
    "This post appears to have been produced by a content farm",
    "The language used in this post is highly formulaic and lacks creativity",
    "The content of this post is unoriginal and uninspired",
    "This post is clearly a rehash of other articles on the same topic",
    "There is little evidence that a human wrote this post",
    "The writing in this post lacks clarity and coherence",
    "This post appears to be a patchwork of other people's ideas and words",
    "The language used in this post is generic and lacks personality",
    "The content of this post is superficial and lacking in detail",
    "It appears that this post was generated using AI",
    "The writing in this post is monotonous and repetitive",
    "There is little variation in the vocabulary used in this post",
    "This post is a cut-and-paste job from other sources",
    "The language used in this post is dry and technical",
    "The content of this post is shallow and uninformative",
    "This post appears to have been created by a text spinner",
    "The writing in this post lacks originality and creativity",
    "There is little evidence of personal input in this post",
    "This post reads like a machine translation",
    "The language used in this post is highly impersonal",
    "The content of this post is derivative and unremarkable",
    "This post appears to have been produced by an automated system",
    "The writing in this post is overly simplistic and lacks nuance",
    "There is little variation in the sentence length and structure of this post",
    "This post appears to be lifted directly from another source",
    "The language used in this post is overly technical and specialized",
    "The content of this post is unoriginal and uninspiring",
    "This post is clearly a copy-paste job",
    "There is little evidence that a human was involved in the creation of this post",
    "The writing in this post lacks the personal touch of a human author",
    "This post appears to be a rehash of existing material on the same topic",
    "The language used in this post is highly formulaic and predictable",
    "The content of this post is superficial and unhelpful",
    "It seems that this post was produced by a content mill",
    "The writing in this post is dull and flavorless",
    "There is little evidence of independent thought in this post",
    "This post appears to have been generated using algorithms",
    "The language used in this post is overly technical and jargony",
    "The content of this post is repetitive and unengaging",
    "This post appears to have been churned out quickly and without care",
    "The writing in this post lacks the spontaneity and creativity of an original piece",
    "There is little variation in the vocabulary and sentence structure of this post",
    "This post is clearly a plagiarism of another work",
    "There is little evidence of creative thinking in this post",
    "The writing in this post lacks the personality and voice of a human author",
    "This post appears to be a regurgitation of existing material with little added value",
    "The language used in this post is dry and impersonal",
    "The content of this post is generic and forgettable",
    "This post appears to have been generated by an automated system with little human input",
    "The writing in this post lacks the spark and inspiration of an original work",
    "There is little variation in the sentence length and structure of this post",
    "This post reads like it was written by a machine",
    "The language used in this post is highly technical and specialized, making it difficult to understand",
    "The content of this post is insubstantial and uninformative",
    "This post appears to be a cut-and-paste job from other sources without any original contribution",
    "There is little evidence of creativity or imagination in this post",
    "The writing in this post is sterile and devoid of emotion",
    "This post is clearly a product of plagiarism or content spinning",
    "The language used in this post is dry and lifeless",
    "The content of this post is superficial and uninteresting",
    "This post appears to have been generated using AI or other automated means",
    "The writing in this post lack soul and passion",
    "There is little variation in the vocabulary used in this post, which makes it repetitive",
    "This post appears to be a copy of others found online",
    "The language used in this post is highly technical and difficult to understand for non-experts",
    "The content of this post is derivative and unimaginative",
    "This post appears to be a cut-and-paste job from a variety of sources",
    "The writing in this post is stilted and unnatural, suggesting it was written by a machine",
    "There is little evidence of critical thinking in this post, making it superficial",
    "This post appears to be a product of plagiarism or a content farm",
    "The language used in this post is overly complicated and technical",
    "The content of this post is repetitive and unoriginal",
    "This post appears to have been produced without any real thought or creativity",
    "The writing in this post lacks the personal touch of a real author, making it unengaging",
    "There is little variation in the sentence lengths and structures of this post",
    "This post is clearly a copy-paste job from other sources without adding anything new",
    "The language used in this post is dull and uninteresting",
    "The content of this post is superficial and lacking depth",
    "This post appears to have been produced by a machine",
    "The writing in this post is devoid of imagination and originality",
    "There is little to no evidence of human input in this post",
    "This post appears to be a patchwork of other people's ideas and words without original contributions",
    "The language used in this post is highly technical and specialized, making it difficult to follow for the layperson",
    "The content of this post is derivative and uninspiring",
    "This post appears to be a rehash of existing material with no added value or original insights",
    "The writing in this post is dry and mechanical, making it difficult to read",
    "There is little variation in the vocabulary and sentence structure of this post, making it repetitive and dull",
    "This post is clearly a product of plagiarism or automated content production",
    "The language used in this post is generic and lacking in personality",
    "The content of this post is unremarkable and forgettable",
    "This post appears to have been churned out quickly with little thought or care",
    "The writing in this post lacks the spontaneity and creativity of original content",
    "There is little variation in the sentence length and structure of this post, making it monotonous",
    "This post appears to be a duplication of existing content without attribution",
    "The language used in this post is overly complicated and technical, making it inaccessible to most readers",
    "The content of this post is superficial and lacking detail or nuance",
    "This post appears to have been lifted directly from another source without any original thinking",
    "The writing in this post lacks personality and style, making it unengaging for the reader",
    "There is little evidence of original thought in this post, suggesting it was produced by a machine.",
  ];

const socksProxy = 'socks5://localhost:9050';
const cookieFile = './cookies.txt';
const report = async (user, url) => {
    const chromeUserAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3';
    console.log('getting');

    // Submit the form using node-curl
    let curl = new Curl();
    //https://api.ipify.org?format=json
    // Set the form URL and form data
    curl.setOpt(Curl.option.URL, 'https://hivewatchers.com/reports/new');
    curl.setOpt(Curl.option.COOKIEFILE, cookieFile);
    curl.setOpt(Curl.option.COOKIEJAR, cookieFile);
    curl.setOpt(Curl.option.PROXY, socksProxy);
    curl.perform();
    let a = await new Promise(res => {
        curl.on('end', function (statusCode, data, headers) {
            console.log(statusCode);
            //console.log(data);
            console.log(headers);
            //this.close();
            res({ data, headers });
            //process.exit();
        });
    })


    const attribs = {};
    //console.log(a);
    const $ = cheerio.load(a.data);
    const input = $('input,textarea');
    const csrf = [...Object.values($('meta'))]
    console.log(csrf[1].attribs.content);
    //console.log({input});
    for (x of Object.keys(input)) {
        if (!input[x].attribs) continue
        attribs[input[x].attribs.name] = input[x].attribs.value;
    }
    attribs['report[details]'] = sentences[Math.floor(Math.random() * sentences.length)];
    attribs['report[post_url]'] = url;
    const types = [
        'Other', 'Spam', 'Plagarism'
    ]
    const supporting = [
        url, ''
    ]
    const username = await new Promise(res => {
        randomFile('data/hive-known', (err, file) => {
            console.log(file);
            res(file)
        })
    })
    attribs['report[reported_by_username]'] = username;
    attribs['report[supporting_link]'] = url;
    attribs['report[abuse_type]'] = types[Math.floor(Math.random() * types.length)];
    const qs = require('qs');
    const options = {
        "headers": {

        },
        withCredentials: true
    };
    console.log({ attribs });
    curl = new Curl();

    // Set the form URL and form data
    console.log(qs.stringify(attribs));
    curl.setOpt(Curl.option.URL, 'https://hivewatchers.com/reports');
    curl.setOpt(Curl.option.POSTFIELDS, qs.stringify(attribs));//POSTFIELDS
    console.log(csrf[1].attribs.content);
    // Set the CSRF token in an HTTP header
    curl.setOpt(Curl.option.HTTPHEADER, [
        "X-CSRF-TOKEN: " + csrf[1].attribs.content,
        "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "accept-language: en-US,en;q=0.9",
        "cache-control: max-age=0",
        "content-type: application/x-www-form-urlencoded",
        "sec-ch-ua: \"Not?A_Brand\";v=\"8\", \"Chromium\";v=\"108\", \"Google Chrome\";v=\"108\"",
        "sec-ch-ua-mobile: ?0",
        "sec-ch-ua-platform: \"Windows\"",
        "sec-fetch-dest: document",
        "sec-fetch-mode: navigate",
        "sec-fetch-site: same-origin",
        "sec-fetch-user: ?1",
        "upgrade-insecure-requests: 1",
        "Referer: https://hivewatchers.com/reports/new",
        "Referrer-Policy: strict-origin-when-cross-origin",
        'user-agent: ' + chromeUserAgent
    ]);

    // Set the cookie file and SOCKS proxy options
    curl.setOpt(Curl.option.COOKIEFILE, cookieFile);
    curl.setOpt(Curl.option.COOKIEJAR, cookieFile);
    curl.setOpt(Curl.option.PROXY, socksProxy);

    // Submit the form
    curl.perform();

    await new Promise(res => {
        curl.on('end', function (statusCode, body, headers) {
            console.log(statusCode);
            console.log(body);
            console.log(headers);

            this.close();
            res();
            process.exit();
        });
    })
    console.log(await tor.post('https://hivewatchers.com/reports', encodeURI(attribs)))
    await tor.torNewSession(); //change tor ip

};
module.exports = { default: report }